// filepath: /Users/eastjun/git/test/self-paced-react/src/RestaurantList.jsx
// Generated by Copilot
import RestaurantItem from "./RestaurantItem";
import koreanCategory from "./assets/images/category-korean.png";
import chineseCategory from "./assets/images/category-chinese.png";
import japaneseCategory from "./assets/images/category-japanese.png";
import westernCategory from "./assets/images/category-western.png";
import asianCategory from "./assets/images/category-asian.png";
import etcCategory from "./assets/images/category-etc.png";

function RestaurantList() {
  return (
    <section className="restaurant-list-container">
      <ul className="restaurant-list">
        <RestaurantItem
          categoryImg={koreanCategory}
          categoryAlt="한식"
          name="피양콩할마니"
          description="평양 출신의 할머니가 수십 년간 운영해온 비지 전문점..."
        />
        <RestaurantItem
          categoryImg={chineseCategory}
          categoryAlt="중식"
          name="친친"
          description="정통 중식의 세계를 펼쳐갑니다."
        />
        <RestaurantItem
          categoryImg={japaneseCategory}
          categoryAlt="일식"
          name="잇쇼우"
          description="정통 자가제면 사누끼 우동이 대표메뉴입니다."
        />
        <RestaurantItem
          categoryImg={westernCategory}
          categoryAlt="양식"
          name="이태리키친"
          description="늘 변화를 추구하는 이태리키친입니다."
        />
        <RestaurantItem
          categoryImg={asianCategory}
          categoryAlt="아시안"
          name="호아빈 삼성점"
          description="푸짐한 양에 국물이 일품인 쌀국수."
        />
        <RestaurantItem
          categoryImg={etcCategory}
          categoryAlt="기타"
          name="도스타코스 선릉점"
          description="멕시칸 캐주얼 그릴."
        />
      </ul>
    </section>
  );
}

export default RestaurantList;
